### ISSUE TITLE
Have you suggested merging this library into official one?

### ISSUE THREAD

**Issue by q2dg** [mathvav/SpeedTrig#1]
Could you send a PR to Arduino.cc's github, don't you think?
Thanks a lot

**Comment by mathvav** [comment]
A few issues:
- I'd have licensing issues with that
- I've noticed that Arduino doesn't close issues that fast on the Arduino repository so it's just better to avoid it.

Also, like mentioned, it calculates a few things differently (degrees vs. radians) and it isn't _always_ as accurate
